version: "3.3"
services:
  pages_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: atanas_va
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pages_db
      POSTGRES_ROOT_PASSWORD: secret_root
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pages_db:/var/lib/psql
# Names our volume
volumes:
  pages_db:
